"""initial schema

Revision ID: 4ce78b747632
Revises:
Create Date: 2026-06-30 09:31:50.964865
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4ce78b747632"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
